'use client'
import Link from 'next/link'
import { FormEvent, useState } from 'react'
import { supabase, supabaseConfigured } from '@/lib/supabaseClient'

type Vehicle={id?:string;plate:string;brand?:string;model?:string;client_name?:string;status?:string}
export default function Search(){const [plate,setPlate]=useState('');const [vehicle,setVehicle]=useState<Vehicle|null>(null);const [tasks,setTasks]=useState<any[]>([]);const [msg,setMsg]=useState('')
 async function submit(e:FormEvent){e.preventDefault();setMsg('');const p=plate.trim().toUpperCase();if(!p)return
   if(!supabaseConfigured){const raw=localStorage.getItem('redline-demo-vehicle');if(raw){const d=JSON.parse(raw);if(d.plate===p){setVehicle(d);setTasks(d.tasks||[]);return}}setVehicle({plate:p,brand:'PEUGEOT',model:'3008',client_name:'Client démo',status:'En cours'});setTasks([{zone:'Pare-chocs avant',work:'Peinture',status:'À faire'},{zone:'Porte avant gauche',work:'Redressage + peinture',status:'En cours'},{zone:'Capot',work:'Peinture',status:'À faire'}]);return}
   const {data,error}=await supabase.from('vehicles').select('*').eq('plate',p).order('created_at',{ascending:false}).limit(1).maybeSingle();if(error||!data){setVehicle(null);setTasks([]);setMsg('Aucun véhicule trouvé.');return}setVehicle(data);const {data:td}=await supabase.from('repair_tasks').select('*').eq('vehicle_id',data.id).order('created_at');setTasks(td||[])
 }
 return <div className="shell"><aside className="sidebar"><img className="logo" src="/logo-redline.png" alt="Redline"/><nav className="nav"><Link href="/dashboard">Accueil</Link><Link href="/vehicles/new">Nouveau véhicule</Link><Link className="active" href="/search">Recherche</Link></nav></aside><main className="main"><h1>Recherche par immatriculation</h1><form className="form" onSubmit={submit}><div className="grid2"><div className="field"><label>Immatriculation</label><input value={plate} onChange={e=>setPlate(e.target.value)} placeholder="AB-123-CD"/></div><div style={{display:'flex',alignItems:'end'}}><button className="btn btn-primary">Rechercher</button></div></div></form>{msg&&<p>{msg}</p>}{vehicle&&<div className="card" style={{marginTop:18}}><h2>{vehicle.plate} — {vehicle.brand} {vehicle.model}</h2><p><b>Client :</b> {vehicle.client_name||'—'} &nbsp; <span className="badge red">{vehicle.status||'En attente'}</span></p><h3>Travaux à effectuer</h3><table className="table"><thead><tr><th>Zone</th><th>Travail</th><th>Statut</th></tr></thead><tbody>{tasks.map((t,i)=><tr key={i}><td>{t.zone}</td><td>{t.work}</td><td>{t.status||'À faire'}</td></tr>)}</tbody></table></div>}</main></div>}
